version: '3.5'

services:
  ### Jesse's Workspace ################################################
  jesse:
    image: salehmir/jesse:latest
    depends_on:
      - postgres
      - redis
    tty: true
    env_file:
      - ../.env
    ports:
      - "9000:9000"
      # Jupyter Port
      - "8888:8888"
    volumes:
      - ../:/home
    container_name: jesse
    command: bash -c "jesse install-live --no-strict && jesse run"
    networks:
      - internal

  ### PostgreSQL ################################################
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=jesse_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jesse_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    container_name: postgres
    networks:
      - internal
  ### Redis ################################################
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    container_name: redis
    command: redis-server --save "" --appendonly no
    networks:
      - internal
  
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - external
      - internal
    env_file:
      - ../.env
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}
      - APP_PORT=${APP_PORT}

networks:
  external:
    external: true
  internal:
    external: false
    driver: bridge

volumes:
  postgres-data:
